/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Lab8java */

#ifndef _Included_Lab8java
#define _Included_Lab8java
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Lab8java
 * Method:    calculateMean
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Lab8java_calculateMean
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Lab8java
 * Method:    calculateSTDDev
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Lab8java_calculateSTDDev
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
